#!/bin/bash

mkdir -p $GOPATH/src/github.com/opsgenie/oec && \
cp -R $OEC_REPO/. $GOPATH/src/github.com/opsgenie/oec && \

cd $GOPATH/src/github.com/opsgenie/oec/windows_service/main && \
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a -o $OUTPUT/oec-packages-win64/oecService64.exe oecService.go && \

cd ~ && \
cd $GOPATH/src/github.com/opsgenie/oec && \
export GIT_COMMIT=$(git rev-list -1 HEAD) && \

cd main && \
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a -ldflags "-X main.OECCommitVersion=$GIT_COMMIT
 -X main.OECVersion=$OEC_VERSION" -o $OUTPUT/oec-packages-win64/OpsgenieEdgeConnector64.exe main.go && \

cd $OUTPUT/oec-packages-win64 && \
zip -r oec-win-amd64.zip ./
